<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 visible-desktop hidden-sm hidden-xs" id="table-vad" style="height:auto;overflow:hidden;text-align:left;">
	<input type="text" class="buscador" />
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="quienes somos" /></div><div><a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id1"><p class="p-widget-v"><?php echo Textos::model()->GetText(437); ?></p></a></div>	
	<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>

	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="misión y visión" /></div><div><a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id6"><p class="p-widget-v"><?php echo Textos::model()->GetText(438); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="trayectoria" /> </div><div><a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id3"><p class="p-widget-v">	<?php echo Textos::model()->GetText(439); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="lucha contra la aftosa" /></div><div> <a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id4"><p class="p-widget-v"><?php echo Textos::model()->GetText(440); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="nuestras plantas" /></div><div> <a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id2"><p class="p-widget-v"><?php echo Textos::model()->GetText(441); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="rse" /></div><div> <a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id5"><p class="p-widget-v"><?php echo Textos::model()->GetText(442); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="proveedores" /></div><div> <a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id9"><p class="p-widget-v"><?php echo Textos::model()->GetText(443); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="proveedores" /></div><div> <a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id11"><p class="p-widget-v"><?php echo Textos::model()->GetText(444); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="prensa" /></div><div><a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id7"> <p class="p-widget-v"><?php echo Textos::model()->GetText(445); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="prensa" /></div><div><a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id10"> <p class="p-widget-v"><?php echo Textos::model()->GetText(446); ?></p></a></div><div class="col-lg-10 col-md-10 col-sm-12 col-xs-12" style="border:1px solid #D9D9D9;float:right;"></div></div>
	
	<div class="tr-widget col-lg-12 col-md-12 col-sm-12 col-xs-12"><div class="td-widget col-lg-2 col-md-2 col-sm-2 col-xs-2" ><img class="img-widget" src="<?php echo Yii::app()->request->baseUrl; ?>/img/widget-vademecum.png" alt="prensa" /></div><div><a href="<?php echo Yii::app()->paisChecker->getBaseUrl(true); ?>/vademecum/id8"> <p class="p-widget-v"><?php echo Textos::model()->GetText(447); ?></p></a></div></div>


</div>